"""add_on_delete_cascade_to_all_fks

Revision ID: 7cd49b61eead
Revises: 92af4051fd0c
Create Date: 2026-03-14 23:22:17.396893

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "7cd49b61eead"
down_revision: Union[str, Sequence[str], None] = "92af4051fd0c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("driver_skill_rel_skill_id_fkey"), "driver_skill_rel", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("driver_skill_rel_driver_id_fkey"), "driver_skill_rel", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "driver_skill_rel", "skills", ["skill_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "driver_skill_rel", "drivers", ["driver_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("driver_track_rel_driver_id_fkey"), "driver_track_rel", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("driver_track_rel_track_id_fkey"), "driver_track_rel", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "driver_track_rel", "drivers", ["driver_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "driver_track_rel", "tracks", ["track_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(op.f("drivers_country_id_fkey"), "drivers", type_="foreignkey")
    op.create_foreign_key(
        None, "drivers", "countries", ["country_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("game_player_hands_user_id_fkey"), "game_player_hands", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("game_player_hands_driver_id_fkey"),
        "game_player_hands",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("game_player_hands_game_id_fkey"), "game_player_hands", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "game_player_hands", "games", ["game_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "game_player_hands", "drivers", ["driver_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "game_player_hands", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("game_rounds_game_id_fkey"), "game_rounds", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("game_rounds_track_id_fkey"), "game_rounds", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("game_rounds_ai_driver_id_fkey"), "game_rounds", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("game_rounds_user_driver_id_fkey"), "game_rounds", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "game_rounds", "drivers", ["ai_driver_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "game_rounds", "drivers", ["user_driver_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "game_rounds", "games", ["game_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "game_rounds", "tracks", ["track_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(op.f("games_user_id_fkey"), "games", type_="foreignkey")
    op.drop_constraint(op.f("games_ai_user_id_fkey"), "games", type_="foreignkey")
    op.create_foreign_key(
        None, "games", "users", ["ai_user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "games", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("team_driver_rel_team_id_fkey"), "team_driver_rel", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("team_driver_rel_driver_id_fkey"), "team_driver_rel", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "team_driver_rel", "drivers", ["driver_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "team_driver_rel", "teams", ["team_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(op.f("teams_country_id_fkey"), "teams", type_="foreignkey")
    op.create_foreign_key(
        None, "teams", "countries", ["country_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(op.f("tracks_country_id_fkey"), "tracks", type_="foreignkey")
    op.create_foreign_key(
        None, "tracks", "countries", ["country_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tracks", type_="foreignkey")
    op.create_foreign_key(
        op.f("tracks_country_id_fkey"), "tracks", "countries", ["country_id"], ["id"]
    )
    op.drop_constraint(None, "teams", type_="foreignkey")
    op.create_foreign_key(
        op.f("teams_country_id_fkey"), "teams", "countries", ["country_id"], ["id"]
    )
    op.drop_constraint(None, "team_driver_rel", type_="foreignkey")
    op.drop_constraint(None, "team_driver_rel", type_="foreignkey")
    op.create_foreign_key(
        op.f("team_driver_rel_driver_id_fkey"),
        "team_driver_rel",
        "drivers",
        ["driver_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("team_driver_rel_team_id_fkey"),
        "team_driver_rel",
        "teams",
        ["team_id"],
        ["id"],
    )
    op.drop_constraint(None, "games", type_="foreignkey")
    op.drop_constraint(None, "games", type_="foreignkey")
    op.create_foreign_key(
        op.f("games_ai_user_id_fkey"), "games", "users", ["ai_user_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("games_user_id_fkey"), "games", "users", ["user_id"], ["id"]
    )
    op.drop_constraint(None, "game_rounds", type_="foreignkey")
    op.drop_constraint(None, "game_rounds", type_="foreignkey")
    op.drop_constraint(None, "game_rounds", type_="foreignkey")
    op.drop_constraint(None, "game_rounds", type_="foreignkey")
    op.create_foreign_key(
        op.f("game_rounds_user_driver_id_fkey"),
        "game_rounds",
        "drivers",
        ["user_driver_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("game_rounds_ai_driver_id_fkey"),
        "game_rounds",
        "drivers",
        ["ai_driver_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("game_rounds_track_id_fkey"), "game_rounds", "tracks", ["track_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("game_rounds_game_id_fkey"), "game_rounds", "games", ["game_id"], ["id"]
    )
    op.drop_constraint(None, "game_player_hands", type_="foreignkey")
    op.drop_constraint(None, "game_player_hands", type_="foreignkey")
    op.drop_constraint(None, "game_player_hands", type_="foreignkey")
    op.create_foreign_key(
        op.f("game_player_hands_game_id_fkey"),
        "game_player_hands",
        "games",
        ["game_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("game_player_hands_driver_id_fkey"),
        "game_player_hands",
        "drivers",
        ["driver_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("game_player_hands_user_id_fkey"),
        "game_player_hands",
        "users",
        ["user_id"],
        ["id"],
    )
    op.drop_constraint(None, "drivers", type_="foreignkey")
    op.create_foreign_key(
        op.f("drivers_country_id_fkey"), "drivers", "countries", ["country_id"], ["id"]
    )
    op.drop_constraint(None, "driver_track_rel", type_="foreignkey")
    op.drop_constraint(None, "driver_track_rel", type_="foreignkey")
    op.create_foreign_key(
        op.f("driver_track_rel_track_id_fkey"),
        "driver_track_rel",
        "tracks",
        ["track_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("driver_track_rel_driver_id_fkey"),
        "driver_track_rel",
        "drivers",
        ["driver_id"],
        ["id"],
    )
    op.drop_constraint(None, "driver_skill_rel", type_="foreignkey")
    op.drop_constraint(None, "driver_skill_rel", type_="foreignkey")
    op.create_foreign_key(
        op.f("driver_skill_rel_driver_id_fkey"),
        "driver_skill_rel",
        "drivers",
        ["driver_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("driver_skill_rel_skill_id_fkey"),
        "driver_skill_rel",
        "skills",
        ["skill_id"],
        ["id"],
    )
    # ### end Alembic commands ###
