"""add_description_to_tracks

Revision ID: ab81a37daef0
Revises: bfe4a3a75c69
Create Date: 2026-03-13 23:07:07.463227

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "ab81a37daef0"
down_revision: Union[str, Sequence[str], None] = "bfe4a3a75c69"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tracks", sa.Column("description", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tracks", "description")
    # ### end Alembic commands ###
